-- Analysis queries for Risk Monitoring Analytics Project
-- All queries are tied to specific risk questions.
-- continuing to use Copilot for this. Will save prompy/reponse in OneNote. instead of being handed the queries I asked it to gradually feed it to me.
